### ISSUE TITLE
How to create .jar of this library

### ISSUE THREAD

**Issue by dotKokott** [digidotcom/xbee-android#11]
I am not sure how to package this project into a .jar file. 

Is there already a configuration for this? (I am new to Gradle, so I am not sure if I am missing something)

Thanks!

**Comment by rubenmoral** [comment]
Hi @dotKokott,

When you make a build, Gradle automatically generates the library in AAR format, which is the default format for Android libraries (see https://developer.android.com/studio/projects/android-library for more info). This file can be found at `xbee_android_library/build/outputs/aar`. If you are developing an Android application that uses the library, you can use this file instead of the JAR.

Anyway, if you still want a JAR file, note that it is contained in the AAR file (called `classes.jar`). You can extract it manually or add a new task in Gradle to generate it automatically, as explained in this question: https://stackoverflow.com/questions/19034466/how-to-create-an-android-library-jar-with-gradle-without-publicly-revealing-sour.

Best regards.
